#####################################################
# Copyright (C) 2014 ADVENTURE Project
# All Rights Reserved
#####################################################
#----------------------------------------------------------------------
# install directory
prefix = ${HOME}/ADVENTURE
DOCDIR = ${prefix}/doc/AdvMates

#----------------------------------------------------------------------
INSTALL = install -c

#----------------------------------------------------------------------
MATES_MANUAL_JP = AdvMates-manual-jp.pdf
MATES_MANUAL_EN =
INSTALL_FILES   = ${MATES_MANUAL_JP} ${MATES_MANUAL_EN}

#----------------------------------------------------------------------
# do not nothing
all	:

#----------------------------------------------------------------------
# install target
install : ${INSTALL_FILES}
	${INSTALL} -d ${DOCDIR}
	${INSTALL} -m 644 ${INSTALL_FILES} ${DOCDIR}
